language: node_js
node_js:
  - "7"
dist: xenial
services:
  - xvfb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
      - calibre
      - fonts-ipafont-gothic
      - fonts-ipafont-mincho
      - fonts-ipaexfont-gothic
      - fonts-ipaexfont-mincho
cache:
  directories:
    - node_modules
install:
  - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"
  - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ~/bin/reviewdog && chmod +x ~/bin/reviewdog
  - npm install
before_script:
  - echo $key_secret_password | gpg --passphrase-fd 0 deploy_key.gpg
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - ssh-add -l
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"
script:
  - reviewdog -conf=.reviewdog.yml -reporter=github-pr-review
  - npm run build
before_deploy:
  - npm run pdf && mv output.pdf TRPGEPUBTemplate_${TRAVIS_TAG}.pdf
  - npm run epub && mv output.epub TRPGEPUBTemplate_${TRAVIS_TAG}.epub
deploy:
  - provider: script
    script: bash ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key:
      secure: "3jGsyAUX06YOfNaU8i8+kT52DSGKYbSsIHh5+ThhOSW4XKM2Q8o3Xhtr1VNWvs+8wsfpC3G+yp8EIO6bydRpNLoj2tP3pwWDGp8FnWU9JgWaaVTjG04LGm3/H6VgNG2tDh9o5E2fy57sEnlQR/32SG9h0ZcVoiKoigQsaVbsRJqkQTXn0lZc1E/4woa92acP3lyhWNHu9mJFmPaiij/qUCUUMEpODsXHyuE4tCc3fn1peGM/PMP9vwVotsV0nSgFLMyQ6lhoEQMysFpCk2vwgAtnT2xrpD/ef2RPU93VQGQu6gDV6tTVeYPcxW72M1p5KbDrVNIF0e4zKAupANmCl1I9uIZ5oXYM3mQ7yjCIfBfUm893uw+oRFB6949H1WCv3Bapq02yVrsYDE+MauzPDLKFFrLqKXNyZBPXOphXrnMlkoCFEJ2q/uq/kQfcUCGvAnXScCIJXbgnp3Y/yaumj8UggCJCntVbmVjahOIsCoWxraRWxL7VeLPq8gTROw5lYCcvarbQlyxSVCuAO3miDmxvJkNU7C1NoKDUUGUeZbdMtUzKtLTYFOSuBeI9a2FRaXC1vbOKCbs0nihLS2wE183CpgeN5cNNfBSgs7tVZ6VQ2di9XcZ8RQD07oRGM+3cMPjrO/RoVnhADTAUIAG0ul2k34//MUdbekekYIoyciQ="
    file_glob: true
    file: TRPGEPUBTemplate*
    skip_cleanup: true
    on:
      tags: true
      repo: tsuyoshicho/TRPGEPUBTemplate
      all_branches: true
env:
  global:
    - REVIEWDOG_VERSION=0.9.11
    - CXX=g++-4.9
    - secure: "AQI5FjotG37njY8GRcXGdIe7uSSjct/57SxjZYVUl+l3o0BSAOwYH3yyf61BRvGrrSQptkmEgwr0sXMAK1dX9umP3DOJFydFdCrxMko8NMOzn2/UBgsxl1h8PuyWrWL28d+kZmft2EmyoikdEdrYZu3spnQ252CXeT7UG6QUNGv220p4zUdJaM2zd2LbmoQVwTne0ae0Y0cOQ34QekF3ydAouoYDqjZtnEoDlMXmuYLPuVPYvKMsSFS8UhCjWsHAoumSbW2nKT33EjYL9G8Hr2D7RfhaG3yRrAhKnBF+YhJY1iNhurlESM3XuD8r2h/nW3+lbz1mEBeSeBiPkwszcEGf2vVq39cGyb+1bwnfIxG7GYq+L2e/o9MuZJmuIAk8SSFwXI0l/AS2J2nEFUm381ZDv5dnvxJZS5n9GhhU7PyHNGrPx4UF+mU2wKCHSApWyt7+3KOPGpLGc3Kn+3CXK74UybJY9ziaBE52F10ynOdDP9Te1ZygKTe/50Xrxb8GoWxOKMPlnppCpZJaerPrny4fqxbLKHc/xMQCNJjc+Ec4uhB45uclqBxmTofzqKUoMvnvcmxumSVFC6OyKYPfWGxE3wt3j4omiyfgo41mjuGdGHc2zCToouYk1vf+vTgfIrn/M/iBhrkoizfY+6262uqQy/bfj4ipl+UcapKvKD8="
    - secure: "b/9pGEnFL0rGpfbcauvdf4yLO8nOp+zwlWXwP8a3waFb7/HDZy/t5VuT6nqrgFIwwBeLE8nYgnb4yhGseEC85XFnrjDS7zncXtc3zOOhDjBLB4H70Qr2W0zVSvn2JdHAFQfi/uFAdPfKkvOxOg331iUgAvwX0PSaAH7R3XWd00O5RFj24XaG5ToC0sslj6csbqfpDNrHNT1cMcc073JNWeea8BYf5f08uvjd6znNqKzupHn9lDHW5V0i8mKHe9/OffGIz7AofnrWXzWbADwmB+SgVU7Q6dUl6+7/95WqtozWsWMq4wT+bfZ6TEJg/Vy1imIvKPeYfvtAg97ZbdgqP7bGXOLHOtJ+ENAc+32Bf6GLduHL3YZZj3ATUOilPweVSni7Br0Ai78YxbtYtHTlsKVSmzPYqm3LmRf9NoBVIVjAK+BC3ON4kWc9EC1jbLf9wiouH5FHYmrcbwWa9Uz4c1hy97fFdlz0sNPFu2WZ6F2T3ge/QSuNWVCfRcBhVkGjVFUSoxl9BBRhK3YWT4x9l0Tlve0S+QTkioCb9Pdj45FKp8/xCVacoA1JWbHnf6md7Wkq7uSkuzC9Fy/fMXMjO03Uxboxr0gS8OdD2p49ksustmea65iF9W9DHK7MdoaMbXVQc0gm1bsGPRSMiPGfcAqL7l8+EAiED9GvzggST1k="
